trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Login to Azure'
  inputs:
    azureSubscription: 'your-azure-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Retrieving Subscription ID..."
      echo "##vso[task.setvariable variable=TF_VAR_subscription_id]$(az account show --query id -o tsv)"

- task: TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    version: '1.5.0'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform plan
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve
  displayName: 'Terraform Apply'
