trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_CLIENT_ID: $(servicePrincipalId)
  ARM_CLIENT_SECRET: $(servicePrincipalKey)
  ARM_SUBSCRIPTION_ID: $(subscriptionId)
  ARM_TENANT_ID: $(tenantId)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'your-azure-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account set --subscription $(ARM_SUBSCRIPTION_ID)
      az aks get-credentials --resource-group $(resource_group_name) --name $(aks_cluster_name)

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.11'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform plan
  displayName: 'Terraform Plan'

- script: terraform apply -auto-approve
  displayName: 'Terraform Apply'